### ISSUE TITLE
We need an editor for git push/pull

### ISSUE THREAD

**Issue by wandell** [isetbio/jupyter-hub-oauth-isetbio#1]
Hi @benjamin-heasly ,

Can you please install one or two editors on the ISETBIO-HUB?

When I commit git typically tries to open an editor for the commit message.  I couldn't find a default editor installed, so the git command fails (at least for me).  I do a little screwing around by hand to make things go OK.  But if we had an editor, things would go better.

Can you install either vim or emacs or both?  To set these as the default for git, users can execute:

```
git config --global core.editor "vim"
git config --global core.editor "emacs"
```

Thanks,
Brian

**Comment by benjamin-heasly** [comment]
Sure.  I'll install some editors.

Another alternative that I usually use is to commit with the `-m` flag

```
git commit -m "my commit message with no editor"
```

**Comment by wandell** [comment]
Thanks.  My comments can be long and sometimes spread across lines and numbered.  I often wonder why I spend time on them, though, rather than just a phrase.

Still an editor would be useful in other cases, too.

Stanford
Sent from mobile device

On Jul 5, 2016, at 8:16 AM, Ben Heasly <notifications@github.com<mailto:notifications@github.com>> wrote:

Sure. I'll install some editors.

Another alternative that I usually use is to commit with the -m flag

git commit -m "my commit message with no editor"

##

**Comment by benjamin-heasly** [comment]
Agreed, should still be useful.

I installed nano, vim, and emacs on the running server.

I also added these to our [Dockerfile](https://github.com/benjamin-heasly/jupyter-hub-oauth-matlab/blob/master/Dockerfile#L34) so they should be in place next time we deploy a server.

**Comment by wandell** [comment]
Thanks very much.
